name: Send News to Telegram (Scheduled)

on:
  schedule:
    - cron: '30 4 * * *'    # 08:00 IRST
    - cron: '30 10 * * *'   # 14:00 IRST
    - cron: '30 16 * * *'   # 20:00 IRST
    - cron: '30 22 * * *'   # 02:00 IRST
  workflow_dispatch:        # اجرا دستی هم فعال باشه

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run News Bot
        env:
          API_KEY: ${{ secrets.NEWS_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python src/news_reader.py
